# Generated by Django 2.1.15 on 2021-02-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='users',
            new_name='user',
        ),
    ]
